#ifndef USRP_RADAR_RELAY_COMMON_HPP
#define USRP_RADAR_RELAY_COMMON_HPP

#define DEFAULT_RADAR_RPC_SERVER_PORT	15432
#define DEFAULT_RADAR_RPC_SERVER_IP	"127.0.0.1"

#endif /* USRP_RADAR_RELAY_COMMON_HPP */
